# When a PR is opened or a push is made, perform an
# architectural inspection on the code using Deptrac.
name: Deptrac

on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.**'
      - 'depfile.yaml'
      - '.github/workflows/inspect.yml'
  push:
    branches:
      - 'develop'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.**'
      - 'depfile.yaml'
      - '.github/workflows/inspect.yml'

jobs:
  build:
    name: Architectural Inspection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer, pecl, phive
          extensions: intl, json, mbstring, xml
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Create composer cache directory
        run: mkdir -p ${{ steps.composer-cache.outputs.dir }}

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Create Deptrac cache directory
        run: mkdir -p build/

      - name: Cache Deptrac results
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-deptrac-${{ github.sha }}
          restore-keys: ${{ runner.os }}-deptrac-

      - name: Install dependencies (limited)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Install dependencies (authenticated)
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
        run: composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Run architectural inspection
        run: |
            sudo phive --no-progress install --global --trust-gpg-keys B8F640134AB1782E,A98E898BB53EB748 qossmic/deptrac
            deptrac analyze --cache-file=build/deptrac.cache
