name: PHPCPD

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'

jobs:
  phpcpd:
    uses: codeigniter4/.github/.github/workflows/phpcpd.yml@main
    with:
      dirs: "src/ tests/"
      options: "--exclude src/Database/Migrations/2020-12-28-223112_create_auth_tables.php --exclude src/Authentication/Authenticators/HmacSha256.php --exclude  tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php"
